{
    'name': 'Maralva Pack - maralva import contacts',
    'version': '19.0.1.0.0',
    'summary': 'Pack maestro Maralva para 19',
    'author': 'Maralva',
    'license': 'AGPL-3',
    'depends': [
        'attachment_indexation',
        'base',
        'base_iban',
        'base_import',
        'base_vat',
        'board',
        'calendar',
        'contacts',
        'l10n_es',
        'mail',
        'mail_plugin',
        'phone_validation',
        'product',
        'resource',
        'spreadsheet',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/res_company_data.xml',
    ],
    'installable': True,
    'application': True,
}
