from . import maralva_migration_batch
from . import maralva_migration_id_map
from . import maralva_migration_log
from . import maralva_migration_import_file
from . import maralva_migration_import_file_company
from . import maralva_migration_import_file_target
from . import maralva_migration_import_group
from . import maralva_migration_import_group_line
from . import maralva_migration_import_wizard
from . import maralva_migration_import_wizard_line
from . import res_partner
